// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenStore.Delivery.Persistence;

#nullable disable

namespace RenStore.Delivery.Persistence.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("address_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apartment_number");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("building_number");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Entrance")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entrance");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<string>("HouseCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("house_code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("street");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("idx_address_application_user_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ApplicationUserId"), "btree");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_address_city_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CityId"), "btree");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("idx_address_country_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CountryId"), "btree");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_address_is_deleted_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("IsDeleted"), "btree");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name_ru");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_city_name");

                    b.Property<string>("NormalizedNameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_city_name_ru");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("country_name");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("country_name_ru");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_country_name");

                    b.Property<string>("NormalizedNameRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_country_name_ru");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("country_phone_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_country_code_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Code"), "btree");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("idx_country_normalized_name_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "btree");

                    b.HasIndex("NormalizedNameRu")
                        .IsUnique()
                        .HasDatabaseName("idx_country_normalized_name_ru_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedNameRu"), "btree");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_order_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<long?>("CurrentSortingCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_sorting_center_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_date");

                    b.Property<int>("DeliveryTariffId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_tariff_id");

                    b.Property<long?>("DestinationSortingCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_sorting_center_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<long?>("PickupPointId")
                        .HasColumnType("bigint")
                        .HasColumnName("pickup_point_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSortingCenterId")
                        .HasDatabaseName("idx_delivery_order_current_sorting_center_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CurrentSortingCenterId"), "btree");

                    b.HasIndex("DeliveryTariffId");

                    b.HasIndex("DestinationSortingCenterId")
                        .HasDatabaseName("idx_delivery_order_destination_sorting_center_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DestinationSortingCenterId"), "btree");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_delivery_order_order_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OrderId"), "btree");

                    b.HasIndex("PickupPointId")
                        .HasDatabaseName("idx_delivery_order_pickup_point_id_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PickupPointId"), "btree");

                    b.ToTable("delivery_orders", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delivery_tariff_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_delivery_tariffs_is_deleted_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("IsDeleted"), "btree");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_delivery_tariffs_type_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Type"), "btree");

                    b.ToTable("delivery_tariffs", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_tracking_history_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("current_location");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_order_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<long?>("PickupPointId")
                        .HasColumnType("bigint")
                        .HasColumnName("pickup_point_id");

                    b.Property<long?>("SortingCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("sorting_center_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("SortingCenterId");

                    b.ToTable("delivery_tracking_history", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.PickupPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pickup_point_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_pickup_point_code_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Code"), "btree");

                    b.ToTable("pickup_points", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.SortingCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sorting_center_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("false");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_sorting_center_code_btree");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Code"), "btree");

                    b.ToTable("sorting_centers", (string)null);
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.Address", b =>
                {
                    b.HasOne("RenStore.Delivery.Domain.Entities.City", "_city")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId");

                    b.HasOne("RenStore.Delivery.Domain.Entities.Country", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RenStore.Delivery.Domain.ValueObjects.FullMultiplyAddress", "_fullAddress", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("full_address_en");

                            b1.Property<string>("Russian")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("full_address_ru");

                            b1.HasKey("AddressId");

                            b1.ToTable("addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("_city");

                    b.Navigation("_fullAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.City", b =>
                {
                    b.HasOne("RenStore.Delivery.Domain.Entities.Country", "_country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_country");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryOrder", b =>
                {
                    b.HasOne("RenStore.Delivery.Domain.Entities.DeliveryTariff", "_tariff")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("DeliveryTariffId");

                    b.Navigation("_tariff");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryTariff", b =>
                {
                    b.OwnsOne("RenStore.Delivery.Domain.ValueObjects.WeightLimitKg", "WeightLimitKg", b1 =>
                        {
                            b1.Property<int>("DeliveryTariffId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Kilograms")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("weight_limit_kg");

                            b1.HasKey("DeliveryTariffId");

                            b1.ToTable("delivery_tariffs");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTariffId");
                        });

                    b.OwnsOne("RenStore.SharedKernal.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<int>("DeliveryTariffId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("InStock")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("DeliveryTariffId");

                            b1.ToTable("delivery_tariffs");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTariffId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("WeightLimitKg")
                        .IsRequired();
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryTracking", b =>
                {
                    b.HasOne("RenStore.Delivery.Domain.Entities.DeliveryOrder", "_deliveryOrder")
                        .WithMany("TrackingHistory")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenStore.Delivery.Domain.Entities.PickupPoint", "_pickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.HasOne("RenStore.Delivery.Domain.Entities.SortingCenter", "_sortingCenter")
                        .WithMany()
                        .HasForeignKey("SortingCenterId");

                    b.Navigation("_deliveryOrder");

                    b.Navigation("_pickupPoint");

                    b.Navigation("_sortingCenter");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.PickupPoint", b =>
                {
                    b.HasOne("RenStore.Delivery.Domain.Entities.Address", "_address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("_address");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.SortingCenter", b =>
                {
                    b.HasOne("RenStore.Delivery.Domain.Entities.Address", "_address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("_address");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.Country", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cities");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryOrder", b =>
                {
                    b.Navigation("TrackingHistory");
                });

            modelBuilder.Entity("RenStore.Delivery.Domain.Entities.DeliveryTariff", b =>
                {
                    b.Navigation("DeliveryOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
